pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: node
    image: node:18
    command:
    - sleep
    args:
    - infinity
  hostAliases:
  - ip: "172.20.0.50"
    hostnames:
    - "gitea.localhost.com"
'''
            defaultContainer 'node'
        }
    }
    stages {
        stage('Unit tests') {
            when {
                anyOf {
                    branch pattern: "feature-*"
                    branch pattern: "develop"
                    branch pattern: "hotfix-*"
                    branch pattern: "release-*"
                    branch pattern: "v*"
                }
            }
            steps {
                container('node') {
                    sh '''
                    yarn install
                    yarn test
                    '''
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline finalizado!'
        }
        success {
            echo 'Pipeline concluído com sucesso!'
        }
        failure {
            echo 'Pipeline falhou. Verifique os logs para mais informações.'
        }
    }
}