apiVersion: v1
kind: Secret
metadata:
  name: gitea-secret
  namespace: gitea
type: Opaque
data:
  # Substitua `password` pelo valor codificado em base64
  password: cjhzQThDUEhEOSFidDZk
  username: Z2l0ZWFfYWRtaW4=